In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import pickle

In [2]:
nude_path = 'E:\More\Images\lesbain anal 1-6'
others_PATHS = ['E:\Memories\Puja-2k16', 'E:\Memories\Puja-2k17', 'E:\Memories\Puja-2k18']

In [3]:
def process(img_url):
    img_array = cv2.imread(img_url)#, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (64, 64))
    new_array = np.array(new_array)
    new_array = new_array/255.0
    return new_array

In [4]:
NL = []

for img_name in os.listdir(nude_path):
    img_path = os.path.join(nude_path, img_name)
    new_array = process(img_path)
    NL.append([new_array, 0])
    

In [5]:
OL = []
for op in others_PATHS:
    for img_name in os.listdir(op):
        if img_name[-4:] in ['.JPG', '.jpg']:
            img_path = os.path.join(op, img_name)
            new_array = process(img_path)
            OL.append([new_array, 1])
    print(op)

E:\Memories\Puja-2k16
E:\Memories\Puja-2k17
E:\Memories\Puja-2k18


In [7]:
training_data = NL + OL
print (len(training_data))
random.shuffle(training_data)

1949


In [8]:
X = []
y = []
for features, label in training_data:
    X.append(features)
    y.append(label)

In [12]:
X = np.array(X).reshape(-1, 64, 64, 3)
print (X[0])

[[[0.58431373 0.61176471 0.6       ]
  [0.60392157 0.62352941 0.61568627]
  [0.60392157 0.62745098 0.62352941]
  ...
  [0.72941176 0.6745098  0.61960784]
  [0.67058824 0.6        0.53333333]
  [0.6745098  0.61960784 0.54901961]]

 [[0.59607843 0.62352941 0.61176471]
  [0.60392157 0.63137255 0.61960784]
  [0.60392157 0.62745098 0.62352941]
  ...
  [0.47058824 0.50588235 0.5254902 ]
  [0.48235294 0.49803922 0.51764706]
  [0.67058824 0.62745098 0.57647059]]

 [[0.60392157 0.62352941 0.61568627]
  [0.60784314 0.63529412 0.61568627]
  [0.60784314 0.63137255 0.62745098]
  ...
  [0.49803922 0.50980392 0.54117647]
  [0.47843137 0.49803922 0.50980392]
  [0.68627451 0.62745098 0.58039216]]

 ...

 [[0.51372549 0.58431373 0.62745098]
  [0.5254902  0.59215686 0.64313725]
  [0.50196078 0.57647059 0.63529412]
  ...
  [0.5254902  0.57254902 0.58039216]
  [0.45882353 0.50196078 0.52156863]
  [0.54901961 0.56470588 0.58431373]]

 [[0.5254902  0.6        0.63137255]
  [0.43137255 0.52941176 0.59215686]


In [13]:
with open('Xrgb.pickle', 'wb') as Xf:
    pickle.dump(X, Xf)
with open('yrgb.pickle', 'wb') as yf:
    pickle.dump(np.array(y), yf)
