In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import matplotlib.pyplot as plt
import numpy as np

import pickle

In [2]:
X = pickle.load(open("Xrgb.pickle", 'rb'))
y = pickle.load(open('yrgb.pickle', 'rb'))

In [3]:
model = Sequential()

model.add(Conv2D(64, (3,3), input_shape = X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss = 'binary_crossentropy', 
              optimizer = 'adam', 
              metrics = ['accuracy']
             )

In [4]:
print(X[0][0], y[0])

[[0.58431373 0.61176471 0.6       ]
 [0.60392157 0.62352941 0.61568627]
 [0.60392157 0.62745098 0.62352941]
 [0.61176471 0.63529412 0.63137255]
 [0.61568627 0.63921569 0.63529412]
 [0.63921569 0.65882353 0.6627451 ]
 [0.65882353 0.69019608 0.70196078]
 [0.75686275 0.77647059 0.77254902]
 [0.74901961 0.7372549  0.71764706]
 [0.70980392 0.69411765 0.69019608]
 [0.74509804 0.72156863 0.69803922]
 [0.63137255 0.61568627 0.58431373]
 [0.64705882 0.61568627 0.58823529]
 [0.73333333 0.70588235 0.67843137]
 [0.67058824 0.64705882 0.61960784]
 [0.76078431 0.7254902  0.70980392]
 [0.7372549  0.70980392 0.67843137]
 [0.68235294 0.6627451  0.60784314]
 [0.65882353 0.63529412 0.60784314]
 [0.72156863 0.69411765 0.67843137]
 [0.62352941 0.60784314 0.56862745]
 [0.7372549  0.71372549 0.69411765]
 [0.74901961 0.72156863 0.68627451]
 [0.15686275 0.23137255 0.31764706]
 [0.24705882 0.34509804 0.44705882]
 [0.25882353 0.3372549  0.46666667]
 [0.27058824 0.36470588 0.4745098 ]
 [0.30196078 0.39215686 0.47

In [5]:
len(X)

1949

In [6]:
#y = np.array(y)
model.fit(X, y, batch_size = 16, validation_split = 0.2,   epochs = 8    )

Train on 1559 samples, validate on 390 samples
Epoch 1/8
1559/1559 [==============================] - 12s 8ms/sample - loss: 0.3741 - accuracy: 0.8371 - val_loss: 0.1983 - val_accuracy: 0.9154
Epoch 2/8
1559/1559 [==============================] - 11s 7ms/sample - loss: 0.2063 - accuracy: 0.9173 - val_loss: 0.1770 - val_accuracy: 0.9333
Epoch 3/8
1559/1559 [==============================] - 11s 7ms/sample - loss: 0.1809 - accuracy: 0.9243 - val_loss: 0.1458 - val_accuracy: 0.9513
Epoch 4/8
1559/1559 [==============================] - 11s 7ms/sample - loss: 0.1130 - accuracy: 0.9622 - val_loss: 0.2806 - val_accuracy: 0.9000
Epoch 5/8
1559/1559 [==============================] - 11s 7ms/sample - loss: 0.0820 - accuracy: 0.9679 - val_loss: 0.0802 - val_accuracy: 0.9615
Epoch 6/8
1559/1559 [==============================] - 11s 7ms/sample - loss: 0.0874 - accuracy: 0.9673 - val_loss: 0.1060 - val_accuracy: 0.9462
Epoch 7/8
1559/1559 [==============================] - 11s 7ms/sample - loss:

In [7]:
model.save('RGB-NSFWvsCOM.model')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: RGB-NSFWvsCOM.model\assets
